# Generated by Django 4.0 on 2021-12-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ammount',
            new_name='amount',
        ),
    ]
